global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "caddy"
    metrics_path: /metrics
    static_configs:
      - targets:
          - proxy:2019

  - job_name: "prometheus"
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9090

  - job_name: "cadvisor"
    metrics_path: /metrics
    static_configs:
      - targets:
          - cadvisor:8080
